steps:
  # Step 1: Build JAR
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']

  # Step 2: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', 'hello-world',
        '--image', 'gcr.io/$PROJECT_ID/hello-world',
        '--platform', 'managed',
        '--allow-unauthenticated'
      ]

images:
  - 'gcr.io/$PROJECT_ID/hello-world'